### ISSUE TITLE
BlockTheSpot install Spotify can not open

### ISSUE THREAD

**Issue by hozansahin** [zwxi/Scoop-Spotify#2] opened 2021-10-31 14:36 UTC
hello,
BlockTheSpot install Spotify can not open. How can i fix it? please help 
`spicetify restore` BlockTheSpot unistall opens when it enters this command

**Comment by o1x3** [comment] 2021-10-31 14:42
https://github.com/khanhas/spicetify-cli/issues/1204

This is most likely the cause of the error. A recent Spotify update messed up with spicetify-cli. The spicetify-cli team has already worked on a fix and it will automatically merged to the repo once they publish it.

Feel free to reopen the issue and comment if this was not your doubt

**Comment by hozansahin** [comment] 2021-10-31 14:45
https://user-images.githubusercontent.com/49832795/139589020-4f3ebeeb-05dc-4642-a9da-d9b266b75d85.mp4

**Comment by hozansahin** [comment] 2021-10-31 14:49
>  Zys3JNZrek.mp4

@nexus-codes

**Comment by o1x3** [comment] 2021-10-31 15:00
> > Zys3JNZrek.mp4
> 
> @nexus-codes

 Yes this is because of the issue with spicetify-cli I mentioned above. I also have the same issue. 

https://github.com/khanhas/spicetify-cli/pull/1208 
This PR to the spicetify-cli repo will fix it. They just need to merge it to the spicetify tool. All we can do it wait for them to merge it, hopefully by today

**Comment by TheGeeKing** [comment] 2021-10-31 15:05
> > > Zys3JNZrek.mp4
> > 
> > 
> > @nexus-codes
> 
> Yes this is because of the issue with spicetify-cli I mentioned above. I also have the same issue.
> 
> [khanhas/spicetify-cli#1208](https://github.com/khanhas/spicetify-cli/pull/1208) This PR to the spicetify-cli repo will fix it. They just need to merge it to the spicetify tool. All we can do it wait for them to merge it, hopefully by today

this issue is not related to the current that spcietify has. In the video, it says genius doesn't have index.js.
The current issue spcietify has still open Spotify but you get a blank screen if you have any custom app. In the video Spotify doesn't even open.

not sure if the fix will be released today.

**Comment by o1x3** [comment] 2021-10-31 15:20
> > > > Zys3JNZrek.mp4
> > > 
> > > 
> > > @nexus-codes
> > 
> > 
> > Yes this is because of the issue with spicetify-cli I mentioned above. I also have the same issue.
> > [khanhas/spicetify-cli#1208](https://github.com/khanhas/spicetify-cli/pull/1208) This PR to the spicetify-cli repo will fix it. They just need to merge it to the spicetify tool. All we can do it wait for them to merge it, hopefully by today
> 
> this issue is not related to the current that spcietify has. In the video, it says genius doesn't have index.js. The current issue spcietify has still open Spotify but you get a blank screen if you have any custom app. In the video Spotify doesn't even open.
> 
> not sure if the fix will be released today.
@hozansahin @TheGeeKing 

Doesn't spicetify include the [Lyrics Plus](https://github.com/khanhas/spicetify-cli/tree/master/CustomApps/lyrics-plus) app to provide lyrics. I never needed to install the genius app after v2

**Comment by TheGeeKing** [comment] 2021-10-31 16:32
> Doesn't spicetify include the [Lyrics Plus](https://github.com/khanhas/spicetify-cli/tree/master/CustomApps/lyrics-plus) app to provide lyrics. I never needed to install the genius app after v2

Genius is built in lyrics-plus in v2.

We don't know which Spotify and Spicetify version @hozansahin uses and at the end of the video he restores his spicetify to genuine Spotify.
He might have genius in config file but not files and so spicetify output an error. 

I still don't know why this issue is discussed here and all the infos needed to help him.

**Comment by o1x3** [comment] 2021-10-31 16:35
> > Doesn't spicetify include the [Lyrics Plus](https://github.com/khanhas/spicetify-cli/tree/master/CustomApps/lyrics-plus) app to provide lyrics. I never needed to install the genius app after v2
> 
> Genius is built in lyrics-plus in v2.
> 
> We don't know which Spotify and Spicetify version @hozansahin uses and at the end of the video he restores his spicetify to genuine Spotify. He might have genius in config file but not files and so spicetify output an error.
> 
> I still don't know why this issue is discussed here and all the infos needed to help him.

@hozansahin I think the best you can do is wait for the patch to spicetify-cli and then reinstall everything

**Comment by hozansahin** [comment] 2021-10-31 16:53
> > > Doesn't spicetify include the [Lyrics Plus](https://github.com/khanhas/spicetify-cli/tree/master/CustomApps/lyrics-plus) app to provide lyrics. I never needed to install the genius app after v2
> > 
> > 
> > Genius is built in lyrics-plus in v2.
> > We don't know which Spotify and Spicetify version @hozansahin uses and at the end of the video he restores his spicetify to genuine Spotify. He might have genius in config file but not files and so spicetify output an error.
> > I still don't know why this issue is discussed here and all the infos needed to help him.
> 
> @hozansahin I think the best you can do is wait for the patch to spicetify-cli and then reinstall everything

okey

**Comment by o1x3** [comment] 2021-10-31 17:09
@hozansahin 

https://github.com/khanhas/spicetify-cli/commit/d55196ddb70bde2556a07abf69c781edd51b4cdb
Issue is fixed but since spicetify didn't increment the version nthe automation didn't trigger an update.

The automated script is set to update the app only if a "release" is published so that every update won't potentially break it.

If they don't publish a release by tomorrow, I'll create a "nightly" version of spicetify with the latest commits which will receive all patches immediately

**Comment by hozansahin** [comment] 2021-10-31 17:16
understand thanks for the information

**Comment by o1x3** [comment] 2021-11-01 08:22
@hozansahin everything should work now, even with normal version of spicetify.

Some errors will show, but it will work. I will try to solve the messages later since everything works now

**Closed as completed by o1x3** 2021-11-01 08:22 UTC
Labels: bug
